version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/server

hooks:
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 20
      runas: root
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 20
      runas: root
  ValidateService:
    - location: scripts/server_validate.sh
      timeout: 100
      runas: root
