version: 0.0
os: linux

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

files:
  - source: /
    destination: /home/ec2-user/server

hooks:
  BeforeInstall:
    - location: scripts/server_clear.sh
      timeout: 20
      runas: ec2-user
  AfterInstall:
    - location: scripts/server_executables_permission.sh
      timeout: 20
      runas: ec2-user
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 20
      runas: ec2-user



#  ValidateService:
#    - location: scripts/server_validate.sh
#      timeout: 60
#      runas: ec2-user
